# GitHub Action: whenever creating a new release of the source code,
# also create a release of the installable plugin.
# Steps to execute:
# - Checkout the source code
# - Run "composer install" to download all dependencies under vendor/
# - Create a .zip file, excluding:
#   - All hidden files (.git, .gitignore, etc)
#   - All development files, ending in .dist
#   - All composer files <= after installing dependencies, no need for them anymore
#   - Markdown files concerning development
#   - Folder build/ <= created only to store the .zip file
#   - Folder dev-helpers/ <= not needed for the plugin
# - Upload the .zip file as an artifact to the action (this step is possibly optional)
# - Upload the .zip file as a release, for download
name: Generate Installable Plugin, and Upload as Release Asset
on:
  release:
    types: [published]
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    permissions:
      contents: write # This gives permission to create releases
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build project
        run: |
          mkdir -p build/sk-live-search
          # Copy all necessary files to the sk-live-search folder
          rsync -av --exclude='.git*' --exclude='node_modules' --exclude='.*' --exclude='CODE_OF_CONDUCT.md' --exclude='CONTRIBUTING.md' --exclude='ISSUE_TEMPLATE.md' --exclude='PULL_REQUEST_TEMPLATE.md' --exclude='*.dist' --exclude='*.yml' --exclude='*.neon' --exclude='composer.*' --exclude='dev-helpers' --exclude='build' --exclude='wporg-assets' --exclude='phpunit*' --exclude='.github' . build/sk-live-search/
          
      - name: Create artifact
        uses: montudor/action-zip@v1
        with:
          args: zip -X -r build/sk-live-search.zip build/sk-live-search
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sk-live-search
          path: build/sk-live-search.zip
          
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/sk-live-search.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
